### ISSUE TITLE
brew tapできない

### ISSUE THREAD

**Issue by 4masaka** [b4b4r07/gomi#13]
とりあえずログを載せます

```
==> Tapping b4b4r07/gomi
Cloning into '/usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-gomi'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-gomi/gomi-sugoi.rb
Calling Hardware.is_64_bit? is disabled!
Use Hardware::CPU.is_64_bit? instead.
/usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-gomi/gomi-sugoi.rb:7:in `<class:Gomi>'
Please report this to the b4b4r07/gomi tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-gomi/gomi.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-gomi/gomi.rb:7:in `<class:Gomi>'
Please report this to the b4b4r07/gomi tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap b4b4r07/gomi: invalid syntax in tap!
```

おそらく `Calling Hardware.is_64_bit? is disabled!` この部分でしょうか...

**Comment by b4b4r07** [comment]
遅くなりすみません。

Now you can install it via homebrew!

```console
$ brew install b4b4r07/tap/gomi
...
...
==> Tapping b4b4r07/tap
Cloning into '/usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-tap'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 4
Unpacking objects: 100% (8/8), done.
Tapped 1 formula (32 files, 25KB).
==> Installing gomi from b4b4r07/tap
==> Downloading https://github.com/b4b4r07/gomi/releases/download/v1.1.1/gomi_darwin_x86_64.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/34890657/37949a00-47c0-11ea-8302-5e1608ef08e6?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
🍺  /usr/local/Cellar/gomi/1.1.1: 4 files, 8.2MB, built in 16 seconds
```
